### ISSUE TITLE
index out of range when looking for '/'

### ISSUE THREAD

**Issue by zer0p1us** [zer0p1us/mod-mender#4]
Input: 
```powershell
mod-mender ./perf_mods_[1.20.X].json
```
Crash log: 
```
Traceback (most recent call last):
  File "D:\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Programs\Python\Python310\Scripts\mod-mender.exe\__main__.py", line 7, in <module>
  File "D:\Programs\Python\Python310\lib\site-packages\mod_mender\main.py", line 184, in main
    os.rename(mod_list_file, get_path_dir(mod_list_file) + "old_"+mod_list_file.rsplit('/', 1)[1])
IndexError: list index out of range
```

System:
windows 10
Python 3.10.1
mod-mender 0.1.0

Likely reason:
Line 184 specifically `"old_"+mod_list_file.rsplit('/', 1)[1]` is looking to split by `/` to get the parent directory, but obviously it won't find one on Windows as it uses `\` (cause ofc it has to be diff), this issue can also occur on Linux if mod-mender is run in the same directory

**Comment by zer0p1us** [comment]
fixed in a8a3e0d8225cd8d598d0b92b5c90120d5255e384
