### ISSUE TITLE
Crush when a `file` property is left empty

### ISSUE THREAD

**Issue by zer0p1us** [zer0p1us/mod-mender#6]
When creating a new mod_list and there is no mod file to point to in `file` the system crushes with the following crash log: 

```
Traceback (most recent call last):
  File "/workspaces/mod-mender/src/mod_mender/main.py", line 193, in <module>
    main(sys.argv)
  File "/workspaces/mod-mender/src/mod_mender/main.py", line 178, in main
    update_jar(current_mod, latest_mod, get_mods_dir(mod_list_file))
  File "/workspaces/mod-mender/src/mod_mender/main.py", line 97, in update_jar
    os.remove(os.path.join(jar_destination, current_version.path))
IsADirectoryError: [Errno 21] Is a directory: 'test/'
```

it would see the issue is because the system only checks if the path exists and not whether it is a file or directory. The `file` being empty the system tries to remove the directory it is in

**Comment by zer0p1us** [comment]
fixed in 0feefc3a5f7555f6e7f95f52ee07e638d2be9f73
